Sprint 14
Maxoscaro/Tracker pull request #2
Opened 2024-11-01 09:44 UTC by Maxoscaro

2024-11-02 08:12 UTC, Kirchberg requested changes
Привет, осталось поправить только один цвет. 

Было бы хорошо не создавать новый PR при новом изменении, ревьюерам легче смотреть на новые изменения, когда мы еще видим наши старые замечания.

2024-11-02 08:12 UTC, Kirchberg commented on TrackerApp/ScheduleScreenViewController.swift
> +        cell.backgroundColor = UIColor(named: "Background")
⚠️ Вот здесь есть ошибка в названии при задании цвета, в Asset у нас называется BackGround, поэтому вот здесь применяется неправильный цвет, не как в макетах. Если поменять строку на BackGround, то цвет станет как в макете, необходимо исправить

2024-11-02 08:12 UTC, Kirchberg commented on TrackerApp/ScheduleScreenViewController.swift
> +        cell.backgroundColor = UIColor(named: "Background")
По этим причинам как раз хорошо было бы иметь файл со всеми цветами, то есть безопасную дизайн-систему в которой ошибемся мы только в одном файле

2024-11-04 09:13 UTC, Maxoscaro commented on TrackerApp/ScheduleScreenViewController.swift
> +        cell.backgroundColor = UIColor(named: "Background")
В Assets стоит Background и при запуске симулятор все отображается корректно

2024-11-05 08:29 UTC, Kirchberg commented on TrackerApp/ScheduleScreenViewController.swift
> +        cell.backgroundColor = UIColor(named: "Background")
Нахожусь на последнем коммите PR-а a83d9acba7c03f6e8965ecec10fddbf8a8a9a479:

<img width="229" alt="image" src="https://github.com/user-attachments/assets/d2a7917f-784a-4039-9b3a-3add81bdd205">

<img width="515" alt="image" src="https://github.com/user-attachments/assets/01d4198d-4852-4885-9d56-de2730c8b80d">

До исправления:
![image](https://github.com/user-attachments/assets/224dd7c8-8d8a-478b-9bbb-015e695e33f9)

После исправления:
![image](https://github.com/user-attachments/assets/0f91bd2f-eb83-47f9-b5c1-ee7b4bacbeef)

2024-11-20 14:31 UTC, closed without merging